src/objects/Discount__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Discounts</relationshipLabel>
        <relationshipName>Discounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Percentes_of_discount__c</fullName>
        <label>Percentes of discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Static_discount__c</fullName>
        <label>Static discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Sales.cls
public with sharing class Sales {

    public Boolean DiscountForAccount {get; set;}
    public List<Discount__c> DiscountsForAccount {get; set;}

    public Sales(){
        DiscountForAccount = false;
        String currentAccountName = UserInfo.getUserId();
        DiscountsForAccount = [SELECT Name,Percentes_of_discount__c,Static_discount__c from Discount__c Where Account__r.Id =: currentAccountName];

        System.Debug(GetDiscount());
    }

    public Boolean CheckAccount(){
        for(Discount__c discount: DiscountsForAccount){
            if(DiscountsForAccount != null){
                DiscountForAccount = true;
                return DiscountForAccount;
            }
        }
        return DiscountForAccount;
    }

    public Discount__c GetDiscount(){
        if(DiscountsForAccount != null){
            return DiscountsForAccount.get(0);
        }
        else { return null; }

    }
}