src/objects/Discount__c.object
<CustomObject>
    <fields>
        <fullName>Percentes_of_discount__c</fullName>
        <label>Percentes of discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Static_discount__c</fullName>
        <label>Static discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <formula>IMAGE( URL_Image__c , &quot;здесь картинка&quot; , 100,100)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_Image__c</fullName>
        <label>URL Image</label>
        <type>Url</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GetProductController.cls
public with sharing class GetProductController {

    public List<Product__c> Products {get; set;}
    public Boolean DiscountForAccount {get; set;}
    public Discount__c Discounts {get; set;}
    public List<Decimal> CostWithSale {get; set;}
    Sales sales = new Sales();
    //public String DescriptionProduct {get; set;}

    public GetProductController(){
        Products = [SELECT Name,Image__c,
                            Title__c, Description__c, Cost__c, URL_Image__c
                    FROM  Product__c
                    LIMIT 10];

        DiscountForAccount = sales.CheckAccount();
//        System.Debug(sales.DiscountsForAccount);
        System.Debug(sales.GetDiscount());
//        if(sales.GetDiscount() != null){
//            Discounts = sales.GetDiscount();
//        }
//        System.Debug(Discounts);


    }

//    public Void Discount(){
//        if(DiscountForAccount = true){
//            for(Product__c product: Products){
//                if(Discounts.get(0).Percentes_of_discount__c != null){
//                    CostWithSale = product.Cost__c -(product.Cost__c*Discounts.get(0).Percentes_of_discount__c/100);
//                }
//                else{
//                    CostWithSale = product.Cost__c -(product.Cost__c*Discounts.get(0).Static_discount__c/100);
//                }
//            }
//        }
//    }
}